default_config = [
    # 'column', 'path', 'localized', 'type', 'default'
    ('title', '$.title', True, 'str', True),
    ('dry_mass', '$.mass', False, 'float', True),
    ('cost', '$.cost', False, 'float', True),
    ('crashTolerance', '$.crashTolerance', False, 'float', True),
    ('maxTemp', '$.maxTemp', False, 'int', True),
    ('techLevel', '$.TechRequired', False, 'str', True),
    ('manufacturer', '$.manufacturer',True, 'str', True),
    ('description', '$.description', True, 'str', True),
    ('author', '$.author', False, 'str', True),
    ('module', '$.module', False, 'str', False),
    ('rescaleFactor', '$.rescaleFactor', False, 'float', True),
    ('minThrust', "$.MODULE[?(@.name==ModuleEngines)].minThrust -> $.MODULE[?(@.name==ModuleEnginesFX)].minThrust", False, 'float', False),
    ('maxThrust', "$.MODULE[?(@.name==ModuleEngines)].maxThrust -> $.MODULE[?(@.name==ModuleEnginesFX)].maxThrust", False, 'float', True),
    ('TWR_dry', 'c("maxThrust") / c("dry_mass")', False, 'None', True),
    ('entryCost', '$.entryCost', False, 'int', True),
    ('attachRules', '$.attachRules', False, 'list[int]', False),
    ('heatConductivity', '$.heatConductivity', False, 'float', True),
    ('skinInternalConductionMult', '$.skinInternalConductionMult', False, 'float', False),
    ('emissiveConstant', '$.emissiveConstant', False, 'float', False),
    ('dragModelType', '$.dragModelType', False, 'str', False),
    ('maximumDrag', '$.maximum_drag', False, 'float', True),
    ('minimumDrag', '$.minimum_drag', False, 'float', True),
    ('angularDrag', '$.angularDrag', False, 'float', True),
    ('diameter', '$.bulkheadProfiles', False, 'list[str]', False),
    ('gimbalTransformName', "$.MODULE[?(@.name==ModuleGimbal)].gimbalTransformName", False, 'str', False),
    ('gimbalRange', "$.MODULE[?(@.name==ModuleGimbal)].gimbalRange", False, 'float', True),
    ('gimbalResponseSpeed', "$.MODULE[?(@.name==ModuleGimbal)].gimbalResponseSpeed", False, 'float', True),
    ('useGimbalResponseSpeed', "$.MODULE[?(@.name==ModuleGimbal)].useGimbalResponseSpeed", False, 'bool', False),
    ('jettisonName', "$.MODULE[?(@.name==ModuleJettison)].jettisonName", False, 'str', False),
    ('bottomNodeName', "$.MODULE[?(@.name==ModuleJettison)].bottomNodeName", False, 'str', False),
    ('isFairing', "$.MODULE[?(@.name==ModuleJettison)].isFairing", False, 'bool', True),
    ('jettisonedObjectMass', "$.MODULE[?(@.name==ModuleJettison)].jettisonedObjectMass", False, 'float', True),
    ('jettisonForce', "$.MODULE[?(@.name==ModuleJettison)].jettisonForce", False, 'float', True),
    ('jettisonDirection', "$.MODULE[?(@.name==ModuleJettison)].jettisonDirection", False, 'list[int]', False),
    ('packedVolume', "$.MODULE[?(@.name==ModuleCargoPart)].packedVolume", False, 'int', True),
    ('alternatorRate', "$.MODULE[?(@.name==ModuleAlternator)].RESOURCE.rate", False, 'float', True),
    ('experimentID', "$.MODULE[?(@.name==ModuleScienceExperiment)].experimentID", False, 'str', True),
    ('experimentActionName', "$.MODULE[?(@.name==ModuleScienceExperiment)].experimentActionName", True, 'str', False),
    ('resetActionName', "$.MODULE[?(@.name==ModuleScienceExperiment)].resetActionName", True, 'str', False),
    ('reviewActionName', "$.MODULE[?(@.name==ModuleScienceExperiment)].reviewActionName", True, 'str', False),
    ('scienceUseStaging', "$.MODULE[?(@.name==ModuleScienceExperiment)].useStaging", False, 'bool', False),
    ('scienceUseActionGroups', "$.MODULE[?(@.name==ModuleScienceExperiment)].useActionGroups", False, 'bool', False),
    ('hideUIwhenUnavailable', "$.MODULE[?(@.name==ModuleScienceExperiment)].hideUIwhenUnavailable", False, 'bool', False),
    ('xmitDataScalar', "$.MODULE[?(@.name==ModuleScienceExperiment)].xmitDataScalar", False, 'str', False),
    ('dataIsCollectable', "$.MODULE[?(@.name==ModuleScienceExperiment)].dataIsCollectable", False, 'bool', True),
    ('collectActionName', "$.MODULE[?(@.name==ModuleScienceExperiment)].collectActionName", True, 'str', False),
    ('interactionRange', "$.MODULE[?(@.name==ModuleScienceExperiment)].interactionRange", False, 'float', True),
    ('rerunnable', "$.MODULE[?(@.name==ModuleScienceExperiment)].rerunnable", False, 'bool', False),
    ('usageReqMaskInternal', "$.MODULE[?(@.name==ModuleScienceExperiment)].usageReqMaskInternal", False, 'int', False),
    ('usageReqMaskExternal', "$.MODULE[?(@.name==ModuleScienceExperiment)].usageReqMaskExternal", False, 'int', False),
    ('exhaustDamage', "$.MODULE[?(@.name==ModuleEngines)].exhaustDamage -> $.MODULE[?(@.name==ModuleEnginesFX)].exhaustDamage", False, 'bool', True),
    ('thrustVectorTransformName', "$.MODULE[?(@.name==ModuleEngines)].thrustVectorTransformName -> $.MODULE[?(@.name==ModuleEnginesFX)].thrustVectorTransformName", False, 'str', False),
    ('heatProduction', "$.MODULE[?(@.name==ModuleEngines)].heatProduction -> $.MODULE[?(@.name==ModuleEnginesFX)].heatProduction", False, 'float', True),
    ('exhaustDamageDistanceOffset', "$.MODULE[?(@.name==ModuleEngines)].exhaustDamageDistanceOffset -> $.MODULE[?(@.name==ModuleEnginesFX)].exhaustDamageDistanceOffset", False, 'float', True),
    # ('resources', '$.RESOURCE', False, 'list[dict]', True),
    ('maxLiquidFuel', '$.RESOURCE[?(@.name==LiquidFuel)].maxAmount', False, 'float', True),
    ('maxOxidizer', '$.RESOURCE[?(@.name==Oxidizer)].maxAmount', False, 'float', True),
    ('maxOre', '$.RESOURCE[?(@.name==Ore)].maxAmount', False, 'float', True),
    ('maxElectricCharge', '$.RESOURCE[?(@.name==ElectricCharge)].maxAmount', False, 'float', True),
    ('maxIntakeAir', '$.RESOURCE[?(@.name==IntakeAir)].maxAmount', False, 'float', True),
    ('maxMonoPropellant', '$.RESOURCE[?(@.name==MonoPropellant)].maxAmount', False, 'float', True),
    ('defaultLiquidFuel', '$.RESOURCE[?(@.name==LiquidFuel)].amount', False, 'float', False),
    ('defaultOxidizer', '$.RESOURCE[?(@.name==Oxidizer)].amount', False, 'float', False),
    ('defaultOre', '$.RESOURCE[?(@.name==Ore)].amount', False, 'float', False),
    ('defaultElectricCharge', '$.RESOURCE[?(@.name==ElectricCharge)].amount', False, 'float', False),
    ('defaultIntakeAir', '$.RESOURCE[?(@.name==IntakeAir)].amount', False, 'float', False),
    ('defaultMonoPropellant', '$.RESOURCE[?(@.name==MonoPropellant)].amount', False, 'float', False),
    ('propellants', '$.MODULE[?(@.name==ModuleEngines)].PROPELLANT..name -> $.MODULE[?(@.name==ModuleEnginesFX)].PROPELLANT..name', False, '*str', True),
    ('node_stack_top', '$.node_stack_top', False, 'list[float]', False),
    ('node_stack_bottom', '$.node_stack_bottom', False, 'list[float]', False),
    ('variant_y_offsets', "$.MODULE[?(@.name==ModulePartVariants)]..VARIANT..NODES.node_stack_bottom.`split(', ', 1, -1)`", False, '*float', True),
    # ('est_height', 'c("node_stack_top").list[1] - c("node_stack_bottom").list[1]', False, "None", True),
    # ('est_height', 'c("node_stack_top").list[1] - c("variant_y_offsets").list[0] -> c("node_stack_top").list[1] - c("node_stack_bottom").list[1]', False, "None", True),
    ('est_height', 'pl.when((c("node_stack_top").list[1] - c("variant_y_offsets").list[0]).is_null()).then(c("node_stack_top").list[1] - c("node_stack_bottom").list[1]).otherwise(c("node_stack_top").list[1] - c("variant_y_offsets").list[0])', False, "None", True),
    ('wet_mass', "c('dry_mass') + ((c('maxLiquidFuel').fill_null(0) * .005 +c('maxOxidizer').fill_null(0) * .005 +c('maxOre').fill_null(0) * .01 +c('maxMonoPropellant').fill_null(0) * .004))", False, 'None', True),
    ('TWR_wet', 'c("maxThrust") / c("wet_mass")', False, 'None', True),
    ('ISP_atm', "$.MODULE[?(@.name==ModuleEngines)].atmosphereCurve.key[1].`split(' ', 1, -1)` -> $.MODULE[?(@.name==ModuleEngines)].atmCurve.key[1].`split(' ', 1, -1)` -> $.MODULE[?(@.name==ModuleEnginesFX)].atmosphereCurve.key[1].`split(' ', 1, -1)` -> $.MODULE[?(@.name==ModuleEnginesFX)].atmCurve.key[1].`split(' ', 1, -1)`", False, 'list[str]', True),
    ('ISP_vac', "$.MODULE[?(@.name==ModuleEngines)].atmosphereCurve.key[0].`split(' ', 1, -1)` -> $.MODULE[?(@.name==ModuleEngines)].atmCurve.key[0].`split(' ', 1, -1)` -> $.MODULE[?(@.name==ModuleEnginesFX)].atmosphereCurve.key[0].`split(' ', 1, -1)` -> $.MODULE[?(@.name==ModuleEnginesFX)].atmCurve.key[0].`split(' ', 1, -1)`", False, 'list[str]', True),
    # ('ISP_curve', "$.MODULE[?(@.name==ModuleEngines)].atmosphereCurve.key[2].`split(' ', 1, -1)` -> $.MODULE[?(@.name==ModuleEngines)].atmCurve.key[2].`split(' ', 1, -1)` -> $.MODULE[?(@.name==ModuleEnginesFX)].atmosphereCurve.key[2].`split(' ', 1, -1)` -> $.MODULE[?(@.name==ModuleEnginesFX)].atmCurve.key[2].`split(' ', 1, -1)`", False, 'list[float]', True),
    ('ISP_vac', 'c("ISP_vac").replace("", -1).cast(float)', False, 'None', True),
    ('ISP_atm', 'c("ISP_atm").replace("", -1).cast(float)', False, 'None', True),
    ('ISP_vac_WR_dry', 'c("ISP_vac") / c("dry_mass")', False, 'None', False),
    ('ISP_vac_WR_wet', 'c("ISP_vac") / c("wet_mass")', False, 'None', False),
    ('ISP_atm_WR_dry', 'c("ISP_atm") / c("dry_mass")', False, 'None', False),
    ('ISP_atm_WR_wet', 'c("ISP_atm") / c("wet_mass")', False, 'None', False),
    ('tags', '$.tags', True, 'str', False),
    ('model_path', '$.MODEL.model', False, 'str', False),
    ('category', '$.category', False, 'str', True),
    ('subcategory', '$.subcategory', False, 'str', True),
    ('path', '$.path', False, 'str', True),
    ('name', '$.name', False, 'str', True),
]










"""
Backup from just before switching to using .split
default_config = [
    # 'column', 'path', 'localized', 'type', 'default'
    ('title', '$.title', True, 'str', True),
    ('dry_mass', '$.mass', False, 'float', True),
    ('cost', '$.cost', False, 'float', True),
    ('crashTolerance', '$.crashTolerance', False, 'float', True),
    ('maxTemp', '$.maxTemp', False, 'int', True),
    ('techLevel', '$.TechRequired', False, 'str', True),
    ('manufacturer', '$.manufacturer',True, 'str', True),
    ('description', '$.description', True, 'str', True),
    ('author', '$.author', False, 'str', True),
    ('module', '$.module', False, 'str', False),
    ('rescaleFactor', '$.rescaleFactor', False, 'float', True),
    ('minThrust', "$.MODULE[?(@.name==ModuleEngines)].minThrust -> $.MODULE[?(@.name==ModuleEnginesFX)].minThrust", False, 'float', False),
    ('maxThrust', "$.MODULE[?(@.name==ModuleEngines)].maxThrust -> $.MODULE[?(@.name==ModuleEnginesFX)].maxThrust", False, 'float', True),
    ('TWR_dry', 'c("maxThrust") / c("dry_mass")', False, 'None', True),
    ('entryCost', '$.entryCost', False, 'int', True),
    ('attachRules', '$.attachRules', False, 'list[int]', False),
    ('heatConductivity', '$.heatConductivity', False, 'float', True),
    ('skinInternalConductionMult', '$.skinInternalConductionMult', False, 'float', False),
    ('emissiveConstant', '$.emissiveConstant', False, 'float', False),
    ('dragModelType', '$.dragModelType', False, 'str', False),
    ('maximumDrag', '$.maximum_drag', False, 'float', True),
    ('minimumDrag', '$.minimum_drag', False, 'float', True),
    ('angularDrag', '$.angularDrag', False, 'float', True),
    ('diameter', '$.bulkheadProfiles', False, 'list[str]', False),
    ('gimbalTransformName', "$.MODULE[?(@.name==ModuleGimbal)].gimbalTransformName", False, 'str', False),
    ('gimbalRange', "$.MODULE[?(@.name==ModuleGimbal)].gimbalRange", False, 'float', True),
    ('gimbalResponseSpeed', "$.MODULE[?(@.name==ModuleGimbal)].gimbalResponseSpeed", False, 'float', True),
    ('useGimbalResponseSpeed', "$.MODULE[?(@.name==ModuleGimbal)].useGimbalResponseSpeed", False, 'bool', False),
    ('jettisonName', "$.MODULE[?(@.name==ModuleJettison)].jettisonName", False, 'str', False),
    ('bottomNodeName', "$.MODULE[?(@.name==ModuleJettison)].bottomNodeName", False, 'str', False),
    ('isFairing', "$.MODULE[?(@.name==ModuleJettison)].isFairing", False, 'bool', True),
    ('jettisonedObjectMass', "$.MODULE[?(@.name==ModuleJettison)].jettisonedObjectMass", False, 'float', True),
    ('jettisonForce', "$.MODULE[?(@.name==ModuleJettison)].jettisonForce", False, 'float', True),
    ('jettisonDirection', "$.MODULE[?(@.name==ModuleJettison)].jettisonDirection", False, 'list[int]', False),
    ('packedVolume', "$.MODULE[?(@.name==ModuleCargoPart)].packedVolume", False, 'int', True),
    ('alternatorRate', "$.MODULE[?(@.name==ModuleAlternator)].RESOURCE.rate", False, 'float', True),
    ('experimentID', "$.MODULE[?(@.name==ModuleScienceExperiment)].experimentID", False, 'str', True),
    ('experimentActionName', "$.MODULE[?(@.name==ModuleScienceExperiment)].experimentActionName", True, 'str', False),
    ('resetActionName', "$.MODULE[?(@.name==ModuleScienceExperiment)].resetActionName", True, 'str', False),
    ('reviewActionName', "$.MODULE[?(@.name==ModuleScienceExperiment)].reviewActionName", True, 'str', False),
    ('scienceUseStaging', "$.MODULE[?(@.name==ModuleScienceExperiment)].useStaging", False, 'bool', False),
    ('scienceUseActionGroups', "$.MODULE[?(@.name==ModuleScienceExperiment)].useActionGroups", False, 'bool', False),
    ('hideUIwhenUnavailable', "$.MODULE[?(@.name==ModuleScienceExperiment)].hideUIwhenUnavailable", False, 'bool', False),
    ('xmitDataScalar', "$.MODULE[?(@.name==ModuleScienceExperiment)].xmitDataScalar", False, 'str', False),
    ('dataIsCollectable', "$.MODULE[?(@.name==ModuleScienceExperiment)].dataIsCollectable", False, 'bool', True),
    ('collectActionName', "$.MODULE[?(@.name==ModuleScienceExperiment)].collectActionName", True, 'str', False),
    ('interactionRange', "$.MODULE[?(@.name==ModuleScienceExperiment)].interactionRange", False, 'float', True),
    ('rerunnable', "$.MODULE[?(@.name==ModuleScienceExperiment)].rerunnable", False, 'bool', False),
    ('usageReqMaskInternal', "$.MODULE[?(@.name==ModuleScienceExperiment)].usageReqMaskInternal", False, 'int', False),
    ('usageReqMaskExternal', "$.MODULE[?(@.name==ModuleScienceExperiment)].usageReqMaskExternal", False, 'int', False),
    ('exhaustDamage', "$.MODULE[?(@.name==ModuleEngines)].exhaustDamage -> $.MODULE[?(@.name==ModuleEnginesFX)].exhaustDamage", False, 'bool', True),
    ('thrustVectorTransformName', "$.MODULE[?(@.name==ModuleEngines)].thrustVectorTransformName -> $.MODULE[?(@.name==ModuleEnginesFX)].thrustVectorTransformName", False, 'str', False),
    ('heatProduction', "$.MODULE[?(@.name==ModuleEngines)].heatProduction -> $.MODULE[?(@.name==ModuleEnginesFX)].heatProduction", False, 'float', True),
    ('exhaustDamageDistanceOffset', "$.MODULE[?(@.name==ModuleEngines)].exhaustDamageDistanceOffset -> $.MODULE[?(@.name==ModuleEnginesFX)].exhaustDamageDistanceOffset", False, 'float', True),
    # ('resources', '$.RESOURCE', False, 'list[dict]', True),
    ('maxLiquidFuel', '$.RESOURCE[?(@.name==LiquidFuel)].maxAmount', False, 'float', True),
    ('maxOxidizer', '$.RESOURCE[?(@.name==Oxidizer)].maxAmount', False, 'float', True),
    ('maxOre', '$.RESOURCE[?(@.name==Ore)].maxAmount', False, 'float', True),
    ('maxElectricCharge', '$.RESOURCE[?(@.name==ElectricCharge)].maxAmount', False, 'float', True),
    ('maxIntakeAir', '$.RESOURCE[?(@.name==IntakeAir)].maxAmount', False, 'float', True),
    ('maxMonoPropellant', '$.RESOURCE[?(@.name==MonoPropellant)].maxAmount', False, 'float', True),
    ('defaultLiquidFuel', '$.RESOURCE[?(@.name==LiquidFuel)].amount', False, 'float', False),
    ('defaultOxidizer', '$.RESOURCE[?(@.name==Oxidizer)].amount', False, 'float', False),
    ('defaultOre', '$.RESOURCE[?(@.name==Ore)].amount', False, 'float', False),
    ('defaultElectricCharge', '$.RESOURCE[?(@.name==ElectricCharge)].amount', False, 'float', False),
    ('defaultIntakeAir', '$.RESOURCE[?(@.name==IntakeAir)].amount', False, 'float', False),
    ('defaultMonoPropellant', '$.RESOURCE[?(@.name==MonoPropellant)].amount', False, 'float', False),
    ('propellants', '$.MODULE[?(@.name==ModuleEngines)].PROPELLANT..name -> $.MODULE[?(@.name==ModuleEnginesFX)].PROPELLANT..name', False, '*str', True),
    ('node_stack_top', '$.node_stack_top', False, 'list[float]', False),
    ('node_stack_bottom', '$.node_stack_bottom', False, 'list[float]', False),
    ('est_height', 'c("node_stack_top").list[1] - c("node_stack_bottom").list[1]', False, "None", True),
    ('wet_mass', "c('dry_mass') + ((c('maxLiquidFuel').fill_null(0) * .005 +c('maxOxidizer').fill_null(0) * .005 +c('maxOre').fill_null(0) * .01 +c('maxMonoPropellant').fill_null(0) * .004))", False, 'None', True),
    ('TWR_wet', 'c("maxThrust") / c("wet_mass")', False, 'None', True),
    ('ISP_atm', "$.MODULE[?(@.name==ModuleEngines)].atmosphereCurve.key[1] -> $.MODULE[?(@.name==ModuleEngines)].atmCurve.key[1] -> $.MODULE[?(@.name==ModuleEnginesFX)].atmosphereCurve.key[1] -> $.MODULE[?(@.name==ModuleEnginesFX)].atmCurve.key[1]", False, 'list[str]', True),
    ('ISP_vac', "$.MODULE[?(@.name==ModuleEngines)].atmosphereCurve.key[0] -> $.MODULE[?(@.name==ModuleEngines)].atmCurve.key[0] -> $.MODULE[?(@.name==ModuleEnginesFX)].atmosphereCurve.key[0] -> $.MODULE[?(@.name==ModuleEnginesFX)].atmCurve.key[0]", False, 'list[str]', True),
    # ('ISP_curve', "$.MODULE[?(@.name==ModuleEngines)].atmosphereCurve.key[2] -> $.MODULE[?(@.name==ModuleEngines)].atmCurve.key[2] -> $.MODULE[?(@.name==ModuleEnginesFX)].atmosphereCurve.key[2] -> $.MODULE[?(@.name==ModuleEnginesFX)].atmCurve.key[2]", False, 'list[float]', True),
    ('ISP_vac', 'c("ISP_vac").str.split(' ').list[1].replace("", -1).replace(None, -1).cast(float)', False, 'None', True),
    ('ISP_atm', 'c("ISP_atm").str.split(" ").list[1].replace("", -1).replace(None, -1).cast(float)', False, 'None', True),
    # TODO: change to wet_mass
    ('ISP_vac_WR_dry', 'c("ISP_vac") / c("dry_mass")', False, 'None', False),
    ('ISP_vac_WR_wet', 'c("ISP_vac") / c("wet_mass")', False, 'None', False),
    ('ISP_atm_WR_dry', 'c("ISP_atm") / c("dry_mass")', False, 'None', False),
    ('ISP_atm_WR_wet', 'c("ISP_atm") / c("wet_mass")', False, 'None', False),
    ('tags', '$.tags', True, 'str', False),
    ('model_path', '$.MODEL.model', False, 'str', False),
    ('category', '$.category', False, 'str', True),
    ('subcategory', '$.subcategory', False, 'str', True),
    ('path', '$.path', False, 'str', True),
    ('name', '$.name', False, 'str', True),
]
 """
